/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_kTBmzCuoU", // Tu User Pool ID correcto
  "aws_user_pools_web_client_id": "78qbqjejduf3svuknrhddtkbp4", // App Client ID
  "oauth": {
    "domain": "post-master.auth.us-east-1.amazoncognito.com",
    "scope": [
        "openid",
        "profile",
        "email",
        "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "https://main.d1sda4wfq545xc.amplifyapp.com/",
    "redirectSignOut": "",
    "responseType": "code"
  },
  "aws_cognito_signup_attributes": [
      "EMAIL",
      "BIRTHDATE",
      "GENDER",
     