/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    region: "us-east-1",
    userPoolId: 'us-east-1_kTBmzCuoU', // Tu User Pool ID
    userPoolWebClientId: '78qbqjejduf3svuknrhddtkbp4', // El App Client ID
    mandatorySignIn: false,
    authenticationFlowType: 'USER_SRP_AUTH',
    oauth: {
      domain: 'https://post-master.auth.us-east-1.amazoncognito.com', // El dominio de Cognito que configuraste
      scope: ['openid', 'profile', 'email', 'profile'], // Scopes de OAuth
      redirectSignIn: 'https://main.d1sda4wfq545xc.amplifyapp.com/', // La URL de redirección después de iniciar sesión (puede cambiar en producción)
      redirectSignOut: 'http://localhost:3000/', // La URL de redirección después de cerrar sesión
      responseType: 'code' // Usamos el flujo Authorization Code Grant
    }
};

export default awsmobile;
